Improve client side logging by implementing RestLiServiceException.toString().
For example, now it might log something like this

com.linkedin.restli.client.RestLiResponseException: Response status 400, serviceErrorMessage: Illegal content type "application/xml", serviceErrorCode: 999

instead of

RestException{_response=RestResponse[headers={X-LinkedIn-Type=com.linkedin.restli.common.ErrorResponse, X-LinkedIn-Error-Response=APP, Content-Length=7828, Server=Jetty(6.1.26)},status=400,entityLength=7828]}

RB=147678
BUGS=SI-683
R=jbetz,cpettitt,tworboys
A=cpettitt,tworboys